### ISSUE TITLE
show git repo name and branch

### ISSUE THREAD

**Issue by rimusz** [Philmod/google-container-slack#7]
is any way to show git repo name and branch?
as right now looking to the slack message you cannot tell where it belongs to.

**Comment by rimusz** [comment]
currently only built images are shown, that's fine when you build images, but if pipeline has no images to build, then slack notification is not really helpful till you click the log url.

**Comment by rimusz** [comment]
created PR #8 to show git repo and branch names in the slack message

**Comment by rimusz** [comment]
any way to show trigger description there too?

**Comment by Philmod** [comment]
For the trigger description, this function would have to fetch the trigger itself from GCB.

**Comment by rimusz** [comment]
solved by #8
